# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0006_auto_20180119_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('identifier', models.CharField(max_length=50, verbose_name='ASIN / UPC')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Produto')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Cliente')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Buy Box')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('fba_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FBA Fee')),
                ('amazon_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarifa Amazon')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default='0.30', max_digits=12, verbose_name='Custo de Envio para Amazon')),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo do Produto')),
                ('profit_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro por Unidade')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Total')),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ROI')),
                ('rank', models.IntegerField(default=0, verbose_name='Rank')),
                ('voi_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo VOI Services')),
                ('condition', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used Like New'), (4, 'Used Very Good'), (5, 'Used Good'), (6, 'Used Acceptable')], null=True, verbose_name='Condição')),
                ('redirect_services', models.ManyToManyField(help_text='Serviços utilizados na preparação do envio.', related_name='stock_product_set', related_query_name='stock_product', to='service.Service', verbose_name='services')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
