# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180213_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='invoices',
            field=models.ManyToManyField(blank=True, help_text='Invoices aos quais este produto pertence.', related_name='stock_product_set', related_query_name='stock_product', to='stock.Invoice', verbose_name='invoices'),
        ),
    ]
