# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180215_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='ASIN / UPC'),
        ),
    ]
