# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180215_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changed_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Data de modificação'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
