# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20180327_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC'),
        ),
    ]
