# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.SmallIntegerField(choices=[(1, 'Não vendido'), (2, 'Vendido')], default=1, verbose_name='Situação')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('sell_date', models.DateField(null=True, verbose_name='Data da Venda')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos aos quais este lote pertence. Deixe em branco para não restringir o acesso à ele.', related_name='lot_set', related_query_name='lot', to='auth.Group', verbose_name='groups')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('identifier', models.CharField(max_length=50, verbose_name='UPC / Código Identificador')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Produto')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Compra')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Venda')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('fba_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tarifa FBA')),
                ('amazon_fee', models.DecimalField(decimal_places=2, default=0.99, max_digits=12, verbose_name='Tarifa Amazon')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.3, max_digits=12, verbose_name='Custo de Envio')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Lot')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
