# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='average_roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ROI Médio'),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Lote'),
        ),
        migrations.AddField(
            model_name='lot',
            name='products_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo dos Produtos'),
        ),
        migrations.AddField(
            model_name='lot',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo do Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro por Unidade'),
        ),
        migrations.AddField(
            model_name='product',
            name='redirect_factor',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=12, verbose_name='Redirecionamento'),
        ),
        migrations.AddField(
            model_name='product',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ROI'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=12, verbose_name='Custo de Envio para Amazon'),
        ),
    ]
