# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import utils.helper


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170611_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='redirect_factor',
            field=models.DecimalField(decimal_places=2, default=1.29, max_digits=12, verbose_name='Redirecionamento'),
        ),
    ]
