# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170613_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='redirect_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Redirecionamento'),
        ),
    ]
