# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_lot_redirect_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='payment_complete',
            field=models.BooleanField(default=False, verbose_name='Situação do Pagamento'),
        ),
    ]
