# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_lot_payment_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='payment_complete',
            field=models.BooleanField(default=False, verbose_name='Pagamento de reserva'),
        ),
    ]
