# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170704_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_fee',
            field=models.DecimalField(decimal_places=2, default='0.99', max_digits=12, verbose_name='Tarifa Amazon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='redirect_factor',
            field=models.DecimalField(decimal_places=2, default='1.29', max_digits=12, verbose_name='Redirecionamento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default='0.30', max_digits=12, verbose_name='Custo de Envio para Amazon'),
        ),
    ]
