# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20171115_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='products_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Produtos'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_complete',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
