# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('store', '0010_auto_20171218_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_group', models.OneToOneField(blank=True, help_text='Grupo ao qual os lotes serão associados por padrão.', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Grupo padrão')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
