# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import store.models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20171227_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.lot_directory_path, validators=[store.validators.validate_file_extension], verbose_name='Imagem'),
        ),
    ]
