# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20171228_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='rank',
        ),
        migrations.AddField(
            model_name='lot',
            name='average_rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rank Médio'),
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='product',
            name='voi_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor item VOI S'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarifa Amazon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name='ASIN / UPC'),
        ),
    ]
