# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-10 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20171028_0949'),
        ('store', '0015_auto_20180104_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotReport',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'proxy': True,
            },
            bases=('store.lot',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='redirect_factor',
        ),
        migrations.AddField(
            model_name='product',
            name='redirect_services',
            field=models.ManyToManyField(help_text='Serviços utilizados na preparação do envio.', related_name='lot_product_set', related_query_name='lot_product', to='service.Service', verbose_name='services'),
        ),
    ]
