# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-10 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20180110_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used Like New'), (4, 'Used Very Good'), (5, 'Used Good'), (6, 'Used Acceptable')], null=True, verbose_name='Condição'),
        ),
    ]
