# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='voi_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo VOI S'),
        ),
        migrations.AddField(
            model_name='lot',
            name='voi_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro VOI S'),
        ),
        migrations.AddField(
            model_name='lot',
            name='voi_roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ROI VOI S (%)'),
        ),
    ]
