# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-19 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20180116_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'permissions': (('view_purchased_lots', 'Pode visualizar lotes comprados'),), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
