# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20180119_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
