# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_lot_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='sell_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Venda'),
        ),
    ]
