# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20180125_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='order_weight',
            field=models.IntegerField(default=0, verbose_name='Peso para ordenação'),
        ),
    ]
