# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_lot_order_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_fake',
            field=models.BooleanField(default=False, verbose_name='Fake'),
        ),
    ]
