# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_lot_is_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('address_1', models.CharField(max_length=60, verbose_name='Endereço linha 1')),
                ('address_2', models.CharField(max_length=60, verbose_name='Endereço linha 2')),
                ('rating', models.PositiveSmallIntegerField(null=True, verbose_name='Avaliação')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Collaborator'),
        ),
    ]
