# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_collaborator_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções em Inglês'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções em Português'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Cliente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fba_fee',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FBA Fee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Buy Box'),
        ),
        migrations.AlterField(
            model_name='product',
            name='voi_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo VOI Services'),
        ),
    ]
