# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20180131_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotreport',
            options={'verbose_name': 'Relatório de Lotes', 'verbose_name_plural': 'Relatório de Lotes'},
        ),
    ]
