# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('store', '0028_auto_20180207_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='stock.Product'),
        ),
    ]
