# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento'),
        ),
    ]
