# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_lot_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lifecycle',
            field=models.SmallIntegerField(choices=[(1, 'Desligado'), (2, 'Ligado'), (3, 'Terminado')], default=1, verbose_name='Lifecycle'),
        ),
    ]
