# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_lot_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lifecycle_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do lifecycle'),
        ),
    ]
