# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_lot_lifecycle_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lifecycle',
            field=models.SmallIntegerField(choices=[(1, 'Desligado'), (2, 'Ligado'), (3, 'Terminado')], default=2, verbose_name='Lifecycle'),
        ),
    ]
