# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-05 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20180303_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'permissions': (('collaborator', 'Colaborador'),), 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
