# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20180305_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lifecycle',
            field=models.SmallIntegerField(choices=[(1, 'Desligado'), (2, 'Ligado'), (4, 'Todos usuários cadastrados'), (3, 'Terminado')], default=2, verbose_name='Lifecycle'),
        ),
    ]
