# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_lot_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pick_ticket',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização na Warehouse'),
        ),
    ]
