# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_product_pick_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC'),
        ),
    ]
