# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_productreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoria'),
        ),
    ]
