# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('send_date', models.DateField(verbose_name='Data Envio')),
                ('status', models.SmallIntegerField(choices=[(1, 'Em Estoque'), (2, 'Enviado')], null=True, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'permissions': (('view_products', 'Pode visualizar Produtos'),),
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('track_number', models.CharField(max_length=50, verbose_name='Rastreamento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
