# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 22:48
from __future__ import unicode_literals

from django.db import migrations


def add_system_groups_permissions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('myauth', '0006_auto_20170415_1229'),
    ]

    operations = [
        migrations.RunPython(add_system_groups_permissions),
    ]
