# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170415_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_products', 'Pode visualizar Produtos'), ('change_product_status', 'Pode editar status do Produto')), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
