# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:08
from __future__ import unicode_literals

from django.db import migrations


def add_admins_group_permission(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170417_0308'),
    ]

    operations = [
        migrations.RunPython(add_admins_group_permission),
    ]
