# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170517_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_partial',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade Parcial'),
        ),
    ]
