# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170520_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_partial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Parcial'),
        ),
    ]
