# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170616_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_condition',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used Like New'), (4, 'Used Very Good'), (5, 'Used Good'), (6, 'Used Acceptable')], null=True, verbose_name='Condição no Recebimento'),
        ),
        migrations.AddField(
            model_name='product',
            name='best_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used Like New'), (4, 'Used Very Good'), (5, 'Used Good'), (6, 'Used Acceptable')], null=True, verbose_name='Condição'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition_comments',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentários da Condição'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='product',
            name='receive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
    ]
