# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170617_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_condition',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used Like New'), (4, 'Used Very Good'), (5, 'Used Good'), (6, 'Used Acceptable')], null=True, verbose_name='Condição no Recebimento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition_comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentários da Condição'),
        ),
    ]
