# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170617_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Encaminhado VOI'), (2, 'Em Estoque VOI'), (99, 'Arquivado'), (100, 'Abandonado')], null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
