# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20170715_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='edd_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AlterField(
            model_name='product',
            name='send_date',
            field=models.DateField(verbose_name='Data da Compra'),
        ),
    ]
