# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20170830_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edd_date',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
    ]
