# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20170831_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_original',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade Original Cadastrada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Encaminhado VOI'), (2, 'Em Estoque VOI'), (99, 'Arquivado'), (100, 'Abandonado')], null=True, verbose_name='Status'),
        ),
    ]
