# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20170922_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pick_ticket',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização na Warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loja'),
        ),
    ]
