# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-10 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_condition'),
        ('product', '0017_auto_20170928_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lot_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
