# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20180131_2008'),
        ('product', '0018_product_lot_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Collaborator', verbose_name='Colaborador'),
        ),
    ]
