# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Produto'),
        ),
    ]
