# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FBA'), (2, 'FBM')], null=True, verbose_name='Estoque'),
        ),
    ]
