# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=50, null=True, verbose_name='ASIN / UPC / EAN'),
        ),
    ]
