# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20180829_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FBA'), (2, 'FBM')], default=1, null=True, verbose_name='Estoque'),
        ),
    ]
