# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190129_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Forwarded'), (2, 'In hand'), (99, 'Filed'), (100, 'Abandoned')], null=True, verbose_name='Status'),
        ),
    ]
