# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-27 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20190219_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoria'),
        ),
    ]
