# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipn', '0007_auto_20160219_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPayPalIPN',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Pagamento',
                'verbose_name': 'Pagamento',
                'proxy': True,
            },
            bases=('ipn.paypalipn',),
        ),
    ]
