# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-07 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agreement_token', models.CharField(max_length=200, verbose_name='Agreement Token')),
                ('agreement_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Agreement ID')),
                ('plan_type', models.SmallIntegerField(choices=[(1, 'VOI Prime'), (2, 'We Create Your Amazon Shipment')], verbose_name='Tipo de plano')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
                'verbose_name': 'Inscrição',
            },
        ),
    ]
