# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-07 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='agreement_token',
        ),
    ]
