# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_subscribe_agreement_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='execute_agreement_url',
            field=models.CharField(db_index=True, default='aa', max_length=200, verbose_name='Execute Agreement URL'),
            preserve_default=False,
        ),
    ]
