# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 13:55
from __future__ import unicode_literals

from django.db import migrations


def add_system_groups_permissions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20170423_1348'),
    ]

    operations = [
        migrations.RunPython(add_system_groups_permissions),
    ]
