# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 13:55
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from shipment.models import Shipment, Product, Package
from django.db.models import Q


def add_system_groups_permissions(apps, schema_editor):
    admin_group = Group.objects.get(name='admins')
    all_users_group = Group.objects.get(name='all_users')
    shipment_content_type = ContentType.objects.get_for_model(Shipment)
    product_content_type = ContentType.objects.get_for_model(Product)
    package_content_type = ContentType.objects.get_for_model(Package)
    perms = Permission.objects.filter(Q(content_type=shipment_content_type) | Q(content_type=product_content_type))
    for p in perms:
        admin_group.permissions.add(p)
        all_users_group.permissions.add(p)
    perms = Permission.objects.filter(content_type=package_content_type)
    for p in perms:
        admin_group.permissions.add(p)
    admin_group.save()
    all_users_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20170423_1348'),
    ]

    operations = [
        migrations.RunPython(add_system_groups_permissions),
    ]
