# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import shipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20170423_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostFormula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=100, verbose_name='Fórmula')),
            ],
            options={
                'verbose_name': 'Cálculo de Envio',
                'verbose_name_plural': 'Cálculo de Envio',
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=shipment.models.user_directory_path, verbose_name='PDF 2'),
        ),
    ]
