# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import shipment.models
import shipment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20170430_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='pdf_1',
            field=models.FileField(upload_to=shipment.models.user_directory_path, validators=[shipment.validators.validate_file_extension], verbose_name='PDF 1'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to=shipment.models.user_directory_path, validators=[shipment.validators.validate_file_extension], verbose_name='PDF 2'),
        ),
    ]
