# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_auto_20170501_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Preparando para Envio'), (2, 'Pagamento Autorizado'), (3, 'Upload PDF 2 Autorizado'), (4, 'Checagens Finais'), (5, 'Enviado')], verbose_name='Status'),
        ),
    ]
