# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_auto_20170503_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='length_units',
            field=models.SmallIntegerField(choices=[(1, 'Centímetros'), (2, 'Milímetros'), (3, 'Inches')], default=3, verbose_name='Unidade de medida de tamanho'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight_units',
            field=models.SmallIntegerField(choices=[(1, 'Libras'), (2, 'Onças'), (3, 'Quilogramas'), (4, 'Gramas')], default=1, verbose_name='Unidade de medida de peso'),
        ),
    ]
