# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0011_auto_20170514_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_products',
            field=models.PositiveIntegerField(verbose_name='Total de Produtos'),
        ),
    ]
