# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shipment.models
import shipment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_auto_20170517_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='pdf_2',
            field=models.FileField(null=True, upload_to=shipment.models.user_directory_path, validators=[shipment.validators.validate_file_extension], verbose_name='Etiqueta da caixa'),
        ),
        migrations.AddField(
            model_name='package',
            name='shipment_tracking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código UPS'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pdf_1',
            field=models.FileField(upload_to=shipment.models.user_directory_path, validators=[shipment.validators.validate_file_extension], verbose_name='Etiqueta do(s) Produto(s)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment'),
        ),
    ]
