# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_auto_20170520_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Warehouse'),
        ),
    ]
