# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0014_auto_20170521_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='warehouse',
            field=models.CharField(max_length=150, null=True, verbose_name='Warehouse'),
        ),
    ]
