# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0015_auto_20170523_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='pdf_2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment',
        ),
    ]
