# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0017_auto_20170526_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
