# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_accounting_accountingpartner'),
        ('shipment', '0018_shipment_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='accounting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Accounting', verbose_name='Fechamento'),
        ),
    ]
