# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0020_auto_20170722_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_products', to='product.Product'),
        ),
    ]
