# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0022_auto_20170722_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
