# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0023_shipment_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Pagamento'),
        ),
    ]
