# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0024_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_sandbox',
            field=models.BooleanField(default=False, verbose_name='Sandbox'),
        ),
    ]
