# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import shipment.models
import shipment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0025_shipment_is_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preparation', models.IntegerField(default=48, help_text='Valor em horas', verbose_name='Preparação para Envio')),
                ('shipment', models.IntegerField(default=24, help_text='Valor em horas', verbose_name='Envio')),
            ],
            options={
                'verbose_name_plural': 'Estimativas',
                'verbose_name': 'Estimativa',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'FBA'), (2, 'MF Amazon'), (3, 'MF eBay'), (4, 'Outro')], null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pdf_1',
            field=models.FileField(null=True, upload_to=shipment.models.user_directory_path, validators=[shipment.validators.validate_file_extension], verbose_name='Etiqueta do(s) Produto(s)'),
        ),
    ]
