# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0026_auto_20170918_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'MF Amazon'), (2, 'MF eBay'), (3, 'Outro')], null=True, verbose_name='Tipo'),
        ),
    ]
