# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0027_auto_20170918_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_date',
            field=models.DateTimeField(null=True, verbose_name='Data de pagamento'),
        ),
    ]
