# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0028_shipment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informações adicionais'),
        ),
    ]
