# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0029_auto_20170924_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimates',
            name='weekends',
            field=models.BooleanField(default=False, verbose_name='Funciona final de semana?'),
        ),
    ]
