# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0031_remove_shipment_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pick_ticket',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização na Warehouse'),
        ),
    ]
