# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0032_package_pick_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
