# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0034_auto_20171029_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'permissions': (('view_shipments', 'Pode visualizar Envios Amazon'), ('view_fbm_shipments', 'Pode visualizar Envios Merchant'), ('add_fbm_shipment', 'Pode adicionar Envios Merchant')), 'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
    ]
