# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0036_productservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productservice',
            options={'verbose_name': 'Serviço Produto', 'verbose_name_plural': 'Serviços Produtos'},
        ),
        migrations.AlterField(
            model_name='productservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_service', to='shipment.Product'),
        ),
    ]
