# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0037_auto_20180120_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_standby',
            field=models.BooleanField(default=False, verbose_name='Aguardando resposta'),
        ),
    ]
