# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20180305_1823'),
        ('shipment', '0038_shipment_is_standby'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Collaborator', verbose_name='Colaborador'),
        ),
    ]
