# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-09 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0039_shipment_collaborator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'permissions': (('view_shipments', 'Pode visualizar Envios Amazon'), ('view_fbm_shipments', 'Pode visualizar Envios Merchant'), ('add_fbm_shipment', 'Pode adicionar Envios Merchant'), ('create_fba_shipment', 'Criar Envio FBA')), 'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
    ]
