# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0041_auto_20180809_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_fba_create',
            field=models.BooleanField(default=False, verbose_name='FBA Prep Criar Envio'),
        ),
    ]
