# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0044_auto_20180812_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
