# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0046_auto_20180904_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='standby_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do aguardando resposta'),
        ),
    ]
