# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180119_1400'),
        ('shipment', '0047_shipment_standby_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_service', to='shipment.Shipment')),
            ],
            options={
                'verbose_name': 'Serviço Envio',
                'verbose_name_plural': 'Serviços Envios',
            },
        ),
    ]
