# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Por unidade', max_digits=12, verbose_name='Preço'),
        ),
    ]
