# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-28 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
    ]
