# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-19 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20171028_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='service',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
