# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 03:19
from __future__ import unicode_literals

from django.db import migrations


def add_site(apps, schema_editor):
    site = apps.get_model('sites', 'Site')
    # mysite = site.objects.get(pk=1)
    # mysite.domain = '54.233.149.84'
    site.objects.create(domain='localhost:9083', name='Vendedor Online Internacional')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_site),
    ]
