# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='partner_cost',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=12, verbose_name='Valor do Parceiro'),
        ),
    ]
