# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20170704_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='params',
            old_name='elapse_one',
            new_name='time_period_one',
        ),
        migrations.RenameField(
            model_name='params',
            old_name='elapse_three',
            new_name='time_period_three',
        ),
        migrations.RenameField(
            model_name='params',
            old_name='elapse_two',
            new_name='time_period_two',
        ),
    ]
