# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0005_auto_20170714_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Fechamento')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fechamentos',
                'verbose_name': 'Fechamento',
            },
        ),
        migrations.CreateModel(
            name='AccountingPartner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=4, verbose_name='Sigla Parceiro')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor USD')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('total_products', models.PositiveIntegerField(verbose_name='Total de produtos')),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Accounting', verbose_name='Fechamento')),
            ],
            options={
                'verbose_name_plural': 'Fechamento - Parceiro',
                'verbose_name': 'Fechamento - Parceiro',
            },
        ),
    ]
