# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_accounting_accountingpartner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingpartner',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiro'},
        ),
        migrations.AlterField(
            model_name='accountingpartner',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
    ]
