# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20170717_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='fgr_cost',
            field=models.DecimalField(decimal_places=2, default=0.29, max_digits=12, verbose_name='Valor Fábio/Gustavo/Roberto'),
        ),
    ]
