# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20170811_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='contact_us_mail_to',
            field=models.EmailField(blank=True, help_text='Separado por ponto e vírgula.', max_length=254, null=True, verbose_name='E-mail fale conosco'),
        ),
    ]
