# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180118_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='is_sandbox',
            field=models.BooleanField(default=False, verbose_name='Sandbox'),
        ),
    ]
