# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myauth.my_user_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='E-mail')),
                ('doc_number', models.CharField(max_length=25, verbose_name='CPF / CNPJ')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('cell_phone', models.CharField(max_length=25, verbose_name='Celular')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', myauth.my_user_manager.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=200, verbose_name='Endereço')),
                ('address_2', models.CharField(max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('zipcode', models.CharField(max_length=15, verbose_name='CEP')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=60, verbose_name='Cidade')),
                ('type', models.SmallIntegerField(verbose_name='Tipo')),
                ('default', models.BooleanField(verbose_name='Padrão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
