# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20170405_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Entrega'), (2, 'Cobrança'), (3, 'Entrega e Cobrança')], verbose_name='Tipo'),
        ),
    ]
