# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20170405_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='doc_number',
            field=models.CharField(max_length=25, verbose_name='CPF'),
        ),
    ]
