# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 12:29
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_system_groups(apps, schema_editor):
    Group.objects.get_or_create(name='all_users')
    admin_group, created = Group.objects.get_or_create(name='admins')
    admin_group.permissions = Permission.objects.all()
    admin_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_auto_20170415_1217'),
    ]

    operations = [
        migrations.RunPython(add_system_groups),
    ]
