# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:02
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from django.db.models import Q
from django.contrib.auth.models import Group
from myauth.models import MyUser


def add_system_superuser(apps, schema_editor):
    system_superuser = MyUser.objects.create_superuser(settings.SYS_SU_USER, 'Administrador', 'Master', '0', '0',
                                                       settings.SYS_SU_PASSWORD)
    system_superuser.is_active = True
    system_superuser.is_verified = True
    system_superuser.groups = Group.objects.filter(Q(name='admins') | Q(name='all_users'))
    system_superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_auto_20170415_1229'),
    ]

    operations = [
        migrations.RunPython(add_system_superuser),
    ]
