# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 03:21
from __future__ import unicode_literals

from django.db import migrations
import myauth.my_user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_auto_20170415_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLotReport',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Relatório Usuário x Lote',
                'verbose_name': 'Relatório Usuário x Lote',
                'proxy': True,
            },
            bases=('myauth.myuser',),
            managers=[
                ('objects', myauth.my_user_manager.MyUserManager()),
            ],
        ),
    ]
