# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_auto_20170415_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('view_admin', 'Pode visualizar Administração'), ('view_users', 'Pode visualizar Usuários')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
