# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_admins_group_permission(apps, schema_editor):
    admin_group = Group.objects.get(name='admins')
    perm = Permission.objects.get(codename='view_users')
    admin_group.permissions.add(perm)
    admin_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_auto_20170416_2353'),
    ]

    operations = [
        migrations.RunPython(add_admins_group_permission),
    ]
