# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:54
from __future__ import unicode_literals

from django.db import migrations


def add_admins_group_permission(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_auto_20170416_2353'),
    ]

    operations = [
        migrations.RunPython(add_admins_group_permission),
    ]
