# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-06 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_myuser_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('space', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Espaço em pés cúbicos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
