# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_auto_20170516_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='partner_identity',
            field=models.CharField(max_length=4, null=True, verbose_name='Sigla parceiro'),
        ),
    ]
