# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-12 10:38
from __future__ import unicode_literals

from django.db import migrations
import string
import random


def gen_from_key(apps, schema_editor):
    MyModel = apps.get_model('myauth', 'MyUser')
    for row in MyModel.objects.all():
        from_key = None
        while from_key is None:
            from_key = ''.join(random.choice(string.ascii_uppercase) for _ in range(4))
            if MyModel.objects.filter(from_key=from_key).exists():
                from_key = None
        row.from_key = from_key
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0011_myuser_from_key'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_from_key, reverse_code=migrations.RunPython.noop),
    ]
