# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('myauth', '0011_myuser_partner_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='partner_identity',
        ),
        migrations.AddField(
            model_name='myuser',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner'),
        ),
    ]
