# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0012_myuser_populate_20180812_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='from_key',
            field=models.CharField(max_length=4, unique=True, verbose_name='FROM'),
        ),
    ]
