# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0013_myuser_removenull_20180812_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='amz_store_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da sua loja na Amazon'),
        ),
    ]
