# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0014_auto_20170629_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
