# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0014_myuser_amz_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language_code',
            field=models.CharField(choices=[('en', 'Inglês'), ('pt', 'Português')], default='pt', max_length=5, verbose_name='Idioma'),
        ),
    ]
