# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0016_auto_20170701_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='terms_conditions',
            field=models.BooleanField(default=False, verbose_name='Termos e Condições'),
        ),
    ]
