# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0018_myuser_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username_internal',
            field=models.CharField(max_length=155, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=150, verbose_name='E-mail'),
        ),
    ]
