# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0020_auto_20170808_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone 2'),
        ),
    ]
