# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=4, verbose_name='Sigla')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Parceiro')),
            ],
        ),
    ]
